create table cities (
    id serial primary key,
    "name" varchar(255) not null
);

insert into cities (name) values
    ('Aguascalientes'),
    ('Mexicali'),
    ('La Paz'),
    ('Campeche'),
    ('Tuxtla Gutiérrez'),
    ('Chihuahua'),
    ('Ciudad de México'),
    ('Saltillo'),
    ('Colima'),
    ('Victoria de Durango'),
    ('Toluca de Lerdo'),
    ('Guanajuato'),
    ('Chilpancingo de los Bravo'),
    ('Pachuca de Soto'),
    ('Guadalajara'),
    ('Morelia'),
    ('Cuernavaca'),
    ('Tepic'),
    ('Monterrey'),
    ('Oaxaca de Juárez'),
    ('Puebla de Zaragoza'),
    ('Santiago de Querétaro'),
    ('Chetumal'),
    ('San Luis Potosí'),
    ('Culiacán Rosales'),
    ('Hermosillo'),
    ('Villahermosa'),
    ('Ciudad Victoria'),
    ('Tlaxcala de Xicohténcatl'),
    ('Xalapa-Enríquez'),
    ('Mérida'),
    ('Zacatecas');