[workspace]
resolver = "2"

members = [
    "auth",
    "users",
    "properties",
    "appointments",
    "file_server",
    "gateway",
]

[workspace.dependencies]
dotenvy = "0.15"
log = "*"
env_logger = "*"
