services:
  properties:
    build: 
      context: .
      dockerfile: properties/Dockerfile
    env_file:
      - properties/.env
    image: properties:latest
    ports:
      - "12004:12000"
    depends_on:
      - properties_db
  properties_db:
    container_name: properties_db
    image: postgres:latest
    restart: always
    env_file:
      - properties/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U inmobify_user -d inmobify_properties"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5435:5432"
    volumes:
      - properties_data:/var/lib/postgresql/data
volumes:
  properties_data:
    driver: local