services:
  users:
    build: 
      context: .
      dockerfile: users/Dockerfile
    env_file:
      - users/.env
    image: users:latest
    ports:
      - "12005:12000"
    depends_on:
      - users_db
  users_db:
    container_name: users_db
    image: postgres:latest
    restart: always
    env_file:
      - users/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U inmobify_user -d inmobify_users"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5436:5432"
    volumes:
      - users_data:/var/lib/postgresql/data
volumes:
  users_data:
    driver: local
    