services:
  appointments:
    build: 
      context: .
      dockerfile: appointments/Dockerfile
    env_file:
      - appointments/.env
    image: appointments:latest
    ports:
      - "12001:12000"
    depends_on:
      - appointments_db
  appointments_db:
    container_name: appointments_db
    image: postgres:latest
    restart: always
    env_file:
      - appointments/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U inmobify_user -d inmobify_appointments"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5433:5432"
    volumes:
      - appointments_data:/var/lib/postgresql/data
  auth:
    build:
      context: .
      dockerfile: auth/Dockerfile
    env_file:
      - auth/.env
    image: auth:latest
    ports:
      - "12002:12000"
    depends_on:
      - users_db
  payments:
    build:
      context: .
      dockerfile: payments/Dockerfile
    env_file:
      - payments/.env
    image: payments:latest
    ports:
      - "12003:12000"
    depends_on:
      - payments_db
  payments_db:
    container_name: payments_db
    image: postgres:latest
    restart: always
    env_file:
      - payments/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U inmobify_user -d inmobify_payments"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5434:5432"
    volumes:
      - payments_data:/var/lib/postgresql/data
  properties:
    build: 
      context: .
      dockerfile: properties/Dockerfile
    env_file:
      - properties/.env
    image: properties:latest
    ports:
      - "12004:12000"
    depends_on:
      - properties_db
  properties_db:
    container_name: properties_db
    image: postgres:latest
    restart: always
    env_file:
      - properties/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U inmobify_user -d inmobify_properties"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5435:5432"
    volumes:
      - properties_data:/var/lib/postgresql/data
  users:
    build: 
      context: .
      dockerfile: users/Dockerfile
    env_file:
      - users/.env
      - auth/.env
    image: users:latest
    ports:
      - "12005:12000"
    depends_on:
      - users_db
  users_db:
    container_name: users_db
    image: postgres:latest
    restart: always
    env_file:
      - users/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U inmobify_user -d inmobify_users"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5436:5432"
    volumes:
      - users_data:/var/lib/postgresql/data
  file_server:
    build: 
      context: .
      dockerfile: file_server/Dockerfile
    image: file_server:latest
    ports:
      - "12006:12000"
    volumes:
      - file_storage:/images
volumes:
  users_data:
    driver: local
  appointments_data:
    driver: local
  properties_data:
    driver: local
  payments_data:
    driver: local
  file_storage:
    driver: local


  


