services:
  auth:
    build:
      context: .
      dockerfile: auth/Dockerfile
    env_file:
      - auth/.env
    image: auth:latest
    ports:
      - "12000:12001"
    depends_on:
      - inmobify_db
  payments:
    build:
      context: .
      dockerfile: payments/Dockerfile
    env_file:
      - payments/.env
    image: payments:latest
    ports:
      - "12000:12002"
    depends_on:
      - inmobify_db
  properties:
    build: 
      context: .
      dockerfile: properties/Dockerfile
    env_file:
      - properties/.env
    image: properties:latest
    ports:
      - "12000:12003"
    depends_on:
      - inmobify_db
  users:
    build: 
      context: .
      dockerfile: users/Dockerfile
    env_file:
      - users/.env
    image: users:latest
    ports:
      - "12000:12004"
    depends_on:
      - inmobify_db
  appointments:
    build: 
      context: .
      dockerfile: appointments/Dockerfile
    env_file:
      - appointments/.env
    image: appointments:latest
    ports:
      - "12000:12005"
    depends_on:
      - inmobify_db
  inmobify_db:
    container_name: inmobify_db
    image: postgres:latest
    restart: always
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U inmobify_user -d inmobify"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5433:5432"
    volumes:
      - inmobify_data:/var/lib/postgresql/data
volumes:
  inmobify_data:
    driver: local


  


