[package]
name = "jwt"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-web-httpauth = "0.6"
jsonwebtoken = "9.3"
serde = { version = "1.0", features = ["derive"] }
dotenvy = "0.15"