[package]
name = "file_server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-files = "0.6.2"
actix-web = "4.3.1"
actix-multipart = "0.6"
futures = "0.3"
actix-cors = "0.7"
tokio = "1.26.0"
serde = { version = "1.0", features = ["derive"] }
